driver:
  name: docker
  privileged: true
  # pin to chef 12 until our cookbooks are 13-safe
  require_chef_omnibus: "12"

platforms:
  - name: centos-6
    driver_config:
      provision_command:
        # remove bogus entry to make fb_fstab happy
        - sed -i '/UUID=/d' /etc/fstab
        # enable EPEL (for stuff like hddtemp)
        - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
        # we need dmidecode for the Ohai shard plugin
        - yum install -y dmidecode
  - name: centos-7
    driver_config:
      provision_command:
        # stub out /etc/fstab for fb_fstab
        - touch /etc/fstab
        # enable EPEL (for stuff like hddtemp)
        - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        # we need dmidecode for the Ohai shard plugin
        - yum install -y dmidecode
      run_command: /usr/sbin/init
  - name: ubuntu-14.04
    driver_config:
      provision_command:
        # we need dmidecode for the Ohai shard plugin
        - apt-get install -y dmidecode
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        # we need dmidecode for the Ohai shard plugin
        - apt-get install -y dmidecode
      run_command: /sbin/init
  - name: debian-8
    driver_config:
      provision_command:
        # we need dmidecode for the Ohai shard plugin
        # we need wget because...
        # https://github.com/test-kitchen/test-kitchen/issues/1018
        # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814070
        - apt-get install -y wget dmidecode
      run_command: /sbin/init
  - name: debian-sid
    driver_config:
      provision_command:
        # we need dmidecode for the Ohai shard plugin
        - apt-get install -y dmidecode
      run_command: /bin/systemd

provisioner:
  name: chef_zero

suites:
  - name: default
    run_list:
      - recipe[fb_init_sample]
